import type { Appearance } from "@clerk/types"

/**
 * Appearance for the standalone auth routes only. The --au-* palette and
 * au-cl-* hooks are defined by AuthScreen's stylesheet. Clerk keeps class
 * names from its provider appearance, so that stylesheet explicitly restores
 * headers, field labels and footer actions above the legacy provider styles.
 */
export const clerkAuthAppearance = {
    layout: {
        socialButtonsPlacement: "bottom",
        socialButtonsVariant: "blockButton",
        animations: true,
        showOptionalFields: false,
    },
    variables: {
        colorPrimary: "var(--au-action, #2456df)",
        colorPrimaryForeground: "#ffffff",
        colorTextOnPrimaryBackground: "#ffffff",
        colorBackground: "var(--au-surface, #ffffff)",
        colorForeground: "var(--au-ink, #172523)",
        colorText: "var(--au-ink, #172523)",
        colorMuted: "var(--au-elevated, #efeee7)",
        colorMutedForeground: "var(--au-muted, #616964)",
        colorTextSecondary: "var(--au-muted, #616964)",
        colorInput: "var(--au-surface, #ffffff)",
        colorInputBackground: "var(--au-surface, #ffffff)",
        colorInputForeground: "var(--au-ink, #172523)",
        colorInputText: "var(--au-ink, #172523)",
        colorNeutral: "var(--au-ink, #172523)",
        colorBorder: "var(--au-line, #dedfd8)",
        colorRing: "var(--au-blue, #2456df)",
        colorDanger: "var(--au-danger, #b42318)",
        colorSuccess: "var(--au-success, #286344)",
        borderRadius: "0.375rem",
        fontFamily: "var(--font-geist-sans), ui-sans-serif, system-ui, sans-serif",
        fontFamilyButtons: "var(--font-geist-sans), ui-sans-serif, system-ui, sans-serif",
        fontSize: "1rem",
    },
    elements: {
        rootBox: "au-cl-root",
        cardBox: "au-cl-card-box",
        card: "au-cl-card",
        header: "au-cl-header",
        headerTitle: "au-cl-title",
        headerSubtitle: "au-cl-subtitle",
        headerBackLink: "au-cl-link",
        backLink: "au-cl-link",
        main: "au-cl-main",
        form: "au-cl-form",
        formContainer: "au-cl-form",
        formHeaderTitle: "au-cl-title",
        formHeaderSubtitle: "au-cl-subtitle",
        socialButtonsRoot: "au-cl-social",
        socialButtons: "au-cl-social",
        socialButtonsBlockButton: "au-cl-social-button",
        socialButtonsBlockButtonText: "au-cl-social-text",
        lastAuthenticationStrategyBadge: "au-cl-badge",
        dividerLine: "au-cl-divider-line",
        dividerText: "au-cl-divider-text",
        formFieldRow: "au-cl-field-row",
        formField: "au-cl-field",
        formFieldLabel: "au-cl-label",
        formFieldInputGroup: "au-cl-input-group",
        formFieldInput: "au-cl-input",
        formFieldInputShowPasswordButton: "au-cl-password-toggle",
        formButtonPrimary: "au-cl-primary",
        formButtonReset: "au-cl-link",
        formFieldAction: "au-cl-link",
        formResendCodeLink: "au-cl-link",
        formFieldErrorText: "au-cl-error",
        formFieldWarningText: "au-cl-hint",
        formFieldInfoText: "au-cl-hint",
        formFieldHintText: "au-cl-hint",
        formFieldSuccessText: "au-cl-success",
        footer: "au-cl-footer",
        footerAction: "au-cl-footer-action",
        footerActionText: "au-cl-footer-text",
        footerActionLink: "au-cl-link",
        footerPages: "au-cl-footer-pages",
        footerPagesLink: "au-cl-link",
        logoBox: "au-cl-logo",
        logoImage: "au-cl-logo-image",
        identityPreview: "au-cl-identity",
        identityPreviewText: "au-cl-identity-text",
        identityPreviewEditButton: "au-cl-link",
        otpCodeField: "au-cl-otp",
        otpCodeFieldInputs: "au-cl-otp-inputs",
        otpCodeFieldInputContainer: "au-cl-otp-container",
        otpCodeFieldInput: "au-cl-otp-input",
        otpCodeFieldErrorText: "au-cl-error",
        otpCodeFieldSuccessText: "au-cl-success",
        alert: "au-cl-alert",
        alertText: "au-cl-alert-text",
        alternativeMethodsBlockButton: "au-cl-alternative-button",
        alternativeMethodsBlockButtonText: "au-cl-social-text",
    },
} satisfies Appearance
