import Image from "next/image"
import Link from "@/components/navigation/transition-link"
import { ArrowUpRight, ArrowUp, Link2, Check, Plus } from "lucide-react"
import { MarketingShell } from "@/components/marketing/marketing-shell"
import { LandingMotion, MotionToggle } from "./brand-motion"
import { StoryBot, type StoryBotName } from "./story-bot"
import { CharacterChooser, ConversationPreview } from "./story-experiences"
import { LegacyHomeLanding } from "./legacy-home-landing"
import { PUBLIC_PLANS } from "@/lib/billing/catalog"
import { messagesFor } from "@/lib/ui-messages"
import type { UiLocale } from "@/lib/ui-locale"
import "./product-story.css"

const stories: { key: string; headline: string; name: string; bot: StoryBotName; welcome: string; question: string; answer: string; action: string; caption: string; alt: string }[] = [
    { key: "cafe", headline: "A better hello. Before the first sip.", name: "Little Hours Café", bot: "Pearl", welcome: "Good coffee. A warmer welcome.", question: "Do you have anything dairy-free?", answer: "Yes — our menu includes oat-milk drinks and dairy-free options. Have a look before you order.", action: "Explore the menu", caption: "From table card to menu. A guest opens your link, asks a question, and finds what to order — while you keep serving.", alt: "A café guest checking her phone beside a cappuccino while a barista works at the counter" },
    { key: "shop", headline: "A little curiosity. A new favorite.", name: "Form & Field", bot: "Nyx", welcome: "Objects with a little more story.", question: "Tell me about your handmade pieces.", answer: "Our collection brings together ceramics and everyday objects from independent makers. Explore the pieces and their details.", action: "View the collection", caption: "From discovery to detail. Give a curious shopper one place to explore your collection and reach your store.", alt: "A shopper holding her phone and a ceramic vase in an independent homewares shop" },
    { key: "studio", headline: "Less wondering. More showing up.", name: "Slow Days Studio", bot: "Ion", welcome: "A little space for yourself.", question: "I’m new to yoga. Where do I start?", answer: "Welcome! Our beginner class is a gentle place to begin. See what to expect, explore the schedule, and contact the studio with questions.", action: "Explore the classes", caption: "From ‘Is this for me?’ to a first visit. Help a newcomer understand your classes before they get in touch.", alt: "A visitor with a yoga mat checking his phone as an instructor welcomes him to a studio" },
]

export function HomeLanding({ locale = "en" }: { locale?: UiLocale }) {
    if (locale === "hi") return <LegacyHomeLanding locale={locale} />
    return <MarketingShell className="product-story" locale={locale}><LandingMotion><main id="main-content">
        <section className="ps-hero ps-wrap" aria-labelledby="ps-title">
            <h1 id="ps-title">Your page.<br /><span>With a voice.</span></h1>
            <p className="ps-lead">One page for your work, your business, your world.<br className="ps-desktop-break" /> An AI guide to help people explore it.</p>
            <Link className="ps-button" href="/sign-up">Create your free page <ArrowUpRight size={18} /></Link><p className="ps-fine">Start free. No card needed.</p>
            <div className="ps-hero-stage"><StoryBot name="Nyx" className="ps-hero-nyx" /><StoryBot name="Ion" className="ps-hero-ion" /><StoryBot name="Pearl" className="ps-hero-pearl" /><div className="ps-bubble ps-bubble-question">“Can you tell me more?”</div><div className="ps-bubble ps-bubble-answer">Of course. Where shall we start?</div></div>
            <p className="ps-hero-caption">More than a link. A place to start a conversation.</p><MotionToggle />
        </section>
        <section className="ps-section ps-cloud" id="product"><div className="ps-wrap" data-reveal><header className="ps-heading ps-centered"><h2>Everything you do.<br />Beautifully introduced.</h2><p>Your story, work, services, and ways to get in touch.<br />All together. All unmistakably you.</p></header><div className="ps-browser"><div className="ps-browser-bar"><span aria-hidden="true">● ● ●</span> introify.com / maya</div><div className="ps-profile"><div><StoryBot name="Doodle" /><h3>Maya Lane.<br />Brand designer.</h3><p>I help thoughtful businesses look and feel like themselves.</p><Link className="ps-button" href="/sign-up">Build your own page <ArrowUpRight size={17} /></Link><ul><li>Selected work <ArrowUpRight size={16} /></li><li>Brand design & websites <ArrowUpRight size={16} /></li><li>Let’s talk <ArrowUpRight size={16} /></li></ul></div><div className="ps-work"><div>make<br />something<br />matter.</div><p>A place for your best work.<br /><span>And the next conversation it starts.</span></p></div></div></div></div></section>
        <section className="ps-section ps-night" id="in-action"><div className="ps-wrap" data-reveal><header className="ps-heading"><h2>You’re busy.<br />Your page is listening.</h2><p>Help visitors explore what you do, with answers grounded in the information you add. Then point them toward the next step.</p></header><ConversationPreview /><p className="ps-fine">You choose the details. Your guide helps people find them.</p></div></section>
        <section className="ps-section" id="stories"><div className="ps-wrap"><header className="ps-heading" data-reveal><h2>Small moments.<br />Real possibilities.</h2><p>At the counter. On the way. Before a first visit.<br />Be there for the questions that help someone take the next step.</p></header>{stories.map(story => <article className="ps-story" key={story.key} data-reveal><h3>{story.headline}</h3><div className={`ps-story-grid ps-story-${story.key}`}><div className="ps-lifestyle"><Image src={`/marketing/everyday/${story.key}.webp`} alt={story.alt} fill sizes="(max-width: 700px) 92vw, (max-width: 1000px) 58vw, 784px" /></div><div className="ps-phone" aria-label={`${story.name} mobile page example`}><div className="ps-phone-status"><span>9:41</span><span aria-hidden="true" className="ps-phone-island" /><span aria-hidden="true">▰</span></div><small>introify.com / {story.key === "cafe" ? "littlehours" : story.key === "shop" ? "formandfield" : "slowdays"}</small><StoryBot name={story.bot} /><h4>{story.name}</h4><p className="ps-phone-welcome">{story.welcome}</p><p className="ps-phone-question">{story.question}</p><p className="ps-phone-answer">{story.answer}</p><span className="ps-phone-action">{story.action} <ArrowUpRight size={15} /></span><div className="ps-phone-composer">Ask {story.name}… <ArrowUp size={18} /></div></div></div><p className="ps-story-caption">{story.caption}</p></article>)}</div></section>
        <section className="ps-section ps-cloud" id="characters"><div className="ps-wrap" data-reveal><header className="ps-heading ps-centered"><h2>Find your kind<br />of character.</h2><p>Cosmic. Curious. Playful. Calm.<br />Choose a guide that feels at home on your page.</p></header><CharacterChooser /></div></section>
        <section className="ps-section" id="share"><div className="ps-wrap" data-reveal><header className="ps-heading"><h2>One link.<br />So many ways in.</h2><p>Put it in your bio. Share it in a message. Add a QR code at your counter.<br />Your next customer can find you wherever the day takes them.</p></header><div className="ps-share-card"><StoryBot name="Pearl" /><div><Link2 size={28} /><h3>introify.com/you</h3><p>Your social bio. Your business card. Your next hello.</p><Link className="ps-button" href="/sign-up">Make your link <ArrowUpRight size={18} /></Link></div></div></div></section>
        <section className="ps-section ps-cloud" id="how-it-works"><div className="ps-wrap" data-reveal><header className="ps-heading"><h2>Your details change.<br />Your page can, too.</h2><p>Start with the essentials. Add your work and offerings.<br />Keep the information your visitors need close at hand.</p></header><div className="ps-editor-scene"><div className="ps-editor"><h3>Your business essentials</h3><dl><div><dt>01 · Introduce yourself</dt><dd>Your name, story, and a character that feels like you.</dd></div><div><dt>02 · Add what you do</dt><dd>Work, products, services, hours, and useful answers.</dd></div><div><dt>03 · Share your page</dt><dd>One link. Ready for your next conversation.</dd></div></dl><Link className="ps-button" href="/sign-up">Start your page <Check size={17} /></Link></div><StoryBot name="Doodle" /></div></div></section>
        <section className="ps-section"><div className="ps-wrap" data-reveal><header className="ps-heading"><h2>Different businesses.<br />One home.</h2><p>A studio. A side project. A second shop.<br />Give each its own page, and keep your work together.</p></header><div className="ps-businesses">{([["Aurum", "Maya Studio", "Brand design & websites"], ["Nyx", "Sunday Coffee", "Your neighborhood café"], ["Pearl", "Slow Days", "Space to slow down"]] as const).map(([bot, name, role]) => <div key={name}><StoryBot name={bot} /><h3>{name}</h3><p>{role}</p></div>)}</div><p className="ps-fine">Business includes up to {PUBLIC_PLANS.find(p => p.id === "business")?.limits.businesses} businesses. Allowances are shared across the account.</p></div></section>
        <section className="ps-section ps-cloud" id="plans"><div className="ps-wrap" data-reveal><header className="ps-heading"><h2>Start small.<br />Grow from there.</h2><p>A free place to begin. More room when you need it.</p></header><div className="ps-plans">{PUBLIC_PLANS.map(plan => <article key={plan.id} data-featured={plan.recommended}><h3>{plan.name}</h3><p className="ps-price"><strong>${plan.monthlyCents / 100}</strong><span>/ month</span></p><p className="ps-muted">{plan.id === "free" ? "For your first page." : plan.id === "pro" ? "For your work and business." : "For a team with more to share."}</p><ul><li>{plan.limits.businesses} {plan.limits.businesses === 1 ? "business" : "businesses"} · {plan.limits.seats} {plan.limits.seats === 1 ? "seat" : "seats"}</li><li>{plan.aiCredits.toLocaleString("en-US")} AI credits / month</li><li>{plan.id === "free" ? "Fast AI replies" : "Fast, Smart & Reasoning AI"}</li><li>{plan.id === "free" ? "Your work, links & offerings" : "Custom branding & instructions"}</li></ul><Link className="ps-text-link" href={plan.id === "free" ? "/sign-up" : "/pricing"}>{plan.id === "free" ? "Start free" : `Explore ${plan.name}`} <ArrowUpRight size={17} /></Link></article>)}</div><p className="ps-fine">Monthly prices in USD. AI credits are shared across the account; usage varies by model.<br />Annual options, plan availability, and full details are on the <Link href="/pricing">pricing page</Link>.</p></div></section>
        <section className="ps-section ps-faq" id="faq"><div className="ps-wrap"><header className="ps-heading"><h2>A few good questions.</h2></header>{messagesFor(locale).home.faq.items.map(([q,a]) => <details key={q}><summary>{q}<Plus size={20} /></summary><p>{a}</p></details>)}</div></section>
        <section className="ps-section ps-night ps-closing"><div className="ps-wrap" data-reveal><p className="ps-eyebrow">A small link. A world of possibility.</p><h2>Your next hello<br />starts here.</h2><p className="ps-lead">Put your work, your world, and a little personality online.<br />Give people a place to find you — and a reason to stay.</p><Link className="ps-button" href="/sign-up">Create your free page <ArrowUpRight size={18} /></Link><p className="ps-fine">Start free. Make it yours. No card required.</p><div className="ps-footer-bots"><StoryBot name="Nyx" /><StoryBot name="Ion" /><StoryBot name="Pearl" /></div></div></section>
    </main></LandingMotion></MarketingShell>
}
