-- AlterTable
ALTER TABLE "ProfileImage" ADD COLUMN IF NOT EXISTS "title" TEXT;
ALTER TABLE "ProfileImage" ADD COLUMN IF NOT EXISTS "body" TEXT;
ALTER TABLE "ProfileImage" ADD COLUMN IF NOT EXISTS "isPublished" BOOLEAN NOT NULL DEFAULT true;
