import type { LucideIcon } from "lucide-react"
import {
    Beef,
    CakeSlice,
    Coffee,
    Cookie,
    Croissant,
    CupSoda,
    Drumstick,
    EggFried,
    Fish,
    Flame,
    GlassWater,
    IceCream,
    Leaf,
    Milk,
    Pizza,
    Salad,
    Sandwich,
    Soup,
    Sparkles,
    Star,
    Tag,
    UtensilsCrossed,
    Wheat,
} from "lucide-react"

const MAP: Record<string, LucideIcon> = {
    veg: Leaf,
    "non-veg": Drumstick,
    nonveg: Drumstick,
    bestsellers: Flame,
    "ratings 4.0+": Star,
    "order again": Sparkles,
    "todays offers": Tag,
    "today's offers": Tag,
    recommended: Star,
    "breakfast & combos": EggFried,
    "burgers & sandwiches": Sandwich,
    "starters & snacks": Cookie,
    "main course": UtensilsCrossed,
    "coffee & beverages": Coffee,
    desserts: IceCream,
    "pizza & pasta": Pizza,
    soup: Soup,
    salads: Salad,
    starter: Cookie,
    "fried rice & noodles": Wheat,
    momo: Soup,
    "fish&prawn": Fish,
    shakes: Milk,
    mocktails: GlassWater,
    bakery: Croissant,
    "cake": CakeSlice,
    coffee: Coffee,
    beverages: CupSoda,
    chicken: Drumstick,
    mutton: Beef,
}

export function categoryIcon(label: string): LucideIcon {
    return MAP[label.trim().toLowerCase()] || UtensilsCrossed
}
