export const clerkAppearance = {
    layout: {
        socialButtonsPlacement: "bottom" as const,
        socialButtonsVariant: "blockButton" as const,
        animations: true,
        unsafe_disableDevelopmentModeWarnings: true,
        showOptionalFields: false,
    },
    variables: {
        colorPrimary: "#00D7FF",
        colorBackground: "transparent",
        colorInputBackground: "rgba(6,8,10,0.78)",
        colorInputText: "#f4f7f6",
        colorText: "#f4f7f6",
        colorTextSecondary: "#8b9591",
        colorTextOnPrimaryBackground: "#061018",
        colorNeutral: "#8b9591",
        colorDanger: "#fb7185",
        borderRadius: "1.25rem",
        fontFamily: "var(--font-geist-sans), ui-sans-serif, system-ui, sans-serif",
        fontSize: "0.9375rem",
    },
    elements: {
        rootBox: "w-full !max-w-none",
        cardBox: "w-full !max-w-none shadow-none",
        card: "w-full !max-w-none !gap-0 rounded-none border-0 bg-transparent p-0 shadow-none",
        header: "!hidden !m-0 !h-0 !p-0 overflow-hidden",
        headerTitle: "hidden",
        headerSubtitle: "hidden",
        socialButtons: "gap-2 overflow-visible",
        socialButtonsBlockButton:
            "relative min-h-11 overflow-visible rounded-full border border-white/8 bg-black/45 py-2.5 text-sm font-medium text-white/90 shadow-none hover:bg-black/60",
        lastAuthenticationStrategyBadge: "hidden",
        socialButtonsBlockButtonText: "text-white",
        dividerLine: "bg-white/10",
        dividerText: "text-[11px] uppercase tracking-[0.18em] text-white/30",
        formFieldLabel: "block w-full text-left text-[11px] font-medium text-white/40",
        formFieldInput:
            "h-11 rounded-full border-white/8 bg-black/50 px-4 text-[16px] text-white placeholder:text-white/28 focus:ring-1 focus:ring-cyan-400/35",
        formButtonPrimary:
            "h-11 rounded-full bg-[#00D7FF] text-sm font-medium text-[#061018] shadow-none hover:bg-[#5ee7ff]",
        formFieldAction: "text-xs text-cyan-300 hover:text-cyan-200",
        footer: { display: "none" },
        footerAction: { display: "none" },
        footerPages: { display: "none" },
        logoBox: { display: "none" },
        logoImage: { display: "none" },
        identityPreview: "rounded-full border-white/10 bg-white/[0.04]",
        identityPreviewText: "text-white",
        identityPreviewEditButton: "text-cyan-300",
        formResendCodeLink: "text-cyan-300",
        otpCodeFieldInput: "h-11 w-11 rounded-xl border-white/10 bg-black/40 text-white",
        alert: "rounded-2xl border-white/10 bg-white/[0.04]",

    },
}
