ALTER TABLE "DigitalProduct" ADD COLUMN IF NOT EXISTS "diet" TEXT;
ALTER TABLE "DigitalProduct" ADD COLUMN IF NOT EXISTS "spiceLevel" INTEGER;
ALTER TABLE "DigitalProduct" ADD COLUMN IF NOT EXISTS "serveWindow" TEXT;
ALTER TABLE "DigitalProduct" ADD COLUMN IF NOT EXISTS "arModelUrl" TEXT;
ALTER TABLE "DigitalProduct" ADD COLUMN IF NOT EXISTS "arUsdzUrl" TEXT;

ALTER TABLE "ServiceOffering" ADD COLUMN IF NOT EXISTS "kind" TEXT NOT NULL DEFAULT 'SESSION';
ALTER TABLE "ServiceOffering" ADD COLUMN IF NOT EXISTS "covers" INTEGER;
